/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Cliente MMS
 */
public class CadastroRestaurante_GUI extends javax.swing.JFrame {
    String nome1;
    String email1;
    long cel1;
    int nascimento1;
    
    String url="jdbc:mysql://localhost/restaurante";
    String username="root";
    String password="";
    /**
     * Creates new form CadastroRestaurante_GUI
     */
    public CadastroRestaurante_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cel = new javax.swing.JFormattedTextField();
        nascimento = new javax.swing.JFormattedTextField();
        sairCadastro = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        info = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 30, 180, 40);

        jLabel2.setText("Nome :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 70, 20);

        jLabel3.setText("Email :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 150, 50, 20);

        jLabel4.setText("Celular:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 200, 60, 20);

        jLabel5.setText("Nascimento :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 70, 20);
        jPanel1.add(nome);
        nome.setBounds(90, 100, 220, 30);
        jPanel1.add(email);
        email.setBounds(90, 150, 220, 30);
        jPanel1.add(cel);
        cel.setBounds(90, 200, 220, 30);
        jPanel1.add(nascimento);
        nascimento.setBounds(110, 250, 250, 30);

        sairCadastro.setText("Sair");
        sairCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(sairCadastro);
        sairCadastro.setBounds(570, 360, 100, 30);

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrar);
        cadastrar.setBounds(20, 350, 120, 30);

        info.setText("Info");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        jPanel1.add(info);
        info.setBounds(580, 10, 90, 30);

        menu.setBackground(new java.awt.Color(0, 153, 51));
        menu.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu);
        menu.setBounds(560, 180, 120, 30);

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        jPanel1.add(consultar);
        consultar.setBounds(180, 350, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(696, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairCadastroActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairCadastroActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new TelaPrincipal_GUI().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        dispose();
        new Consulta_GUI().setVisible(true);
    }//GEN-LAST:event_consultarActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        dispose();
        new Info_GUI().setVisible(true);
    }//GEN-LAST:event_infoActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
         nome1=nome.getText();
         email1=email.getText();
         cel1=Long.valueOf(cel.getText());
         
         //nascimento1=Integer.valueOf(nascimento.getText());
         
         controller.Conexao.testa();
        
              try{
            Connection con=null;
                    try{
                        con=(Connection) DriverManager.getConnection(url,username,password);
                    }catch(SQLException ex){
                        Logger.getLogger(CadastroRestaurante_GUI.class.getName()).log(Level.SEVERE,null,ex);
                    }
                    
                    String sql="INSERT INTO cliente (nome_cliente,email_cliente,tel_cliente) values('"+nome1+"','"+email1+"','"+cel1+"')";
                    try{
                        PreparedStatement inserir= (PreparedStatement) con.prepareStatement(sql);
                        inserir.execute();
                        
                        JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso\n","",-1);
                        nome.setText("");
                        email.setText("");
                        cel.setText("");
                        nascimento.setText("");
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null,"\n Falha na inserção\n" ,"Erro", 0);
                        
                    }
              }catch(NumberFormatException erro){
                  JOptionPane.showMessageDialog(null,"\nErro de numero\n","",0);
                  cel.setText("");
              }
        
    }//GEN-LAST:event_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroRestaurante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroRestaurante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroRestaurante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroRestaurante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroRestaurante_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JFormattedTextField cel;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField email;
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu;
    private javax.swing.JFormattedTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JButton sairCadastro;
    // End of variables declaration//GEN-END:variables
}
