/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Cliente MMS
 */
public class Consulta_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Consulta_GUI
     */
    public Consulta_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        voltarConsulta = new javax.swing.JButton();
        sairConsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigoC = new javax.swing.JTextField();
        nomeC = new javax.swing.JTextField();
        emailC = new javax.swing.JTextField();
        telC = new javax.swing.JTextField();
        btnConcultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 10, 930, 100);

        voltarConsulta.setText("Voltar");
        voltarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(voltarConsulta);
        voltarConsulta.setBounds(0, 420, 120, 23);

        sairConsulta.setText("SAIR");
        sairConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(sairConsulta);
        sairConsulta.setBounds(810, 420, 90, 23);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Código :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 170, 70, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Nome :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 220, 60, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Email :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 280, 60, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Telefone :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 330, 80, 20);

        codigoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoCActionPerformed(evt);
            }
        });
        jPanel1.add(codigoC);
        codigoC.setBounds(120, 170, 100, 30);
        jPanel1.add(nomeC);
        nomeC.setBounds(120, 230, 210, 30);
        jPanel1.add(emailC);
        emailC.setBounds(120, 280, 220, 30);
        jPanel1.add(telC);
        telC.setBounds(120, 330, 230, 30);

        btnConcultar.setText("Consultar");
        jPanel1.add(btnConcultar);
        btnConcultar.setBounds(750, 160, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(933, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairConsultaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairConsultaActionPerformed

    private void voltarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarConsultaActionPerformed
        // TODO add your handling code here:
        dispose();
        new CadastroRestaurante_GUI().setVisible(true);
    }//GEN-LAST:event_voltarConsultaActionPerformed

    private void codigoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcultar;
    private javax.swing.JTextField codigoC;
    private javax.swing.JTextField emailC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeC;
    private javax.swing.JButton sairConsulta;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField telC;
    private javax.swing.JButton voltarConsulta;
    // End of variables declaration//GEN-END:variables
}
