/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author Cliente MMS
 */
public class TelaPrincipal_GUI extends javax.swing.JFrame {
    public static int num;

    /**
     * Creates new form TelaPrincipal_GUI
     */
    public TelaPrincipal_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        cardapio = new javax.swing.JLabel();
        btnPPrincipais = new javax.swing.JButton();
        btnPizzas = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        btnSobremesas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAulas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        voltarTelaPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        btnSair.setBackground(new java.awt.Color(204, 204, 255));
        btnSair.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(730, 300, 110, 23);

        cardapio.setBackground(new java.awt.Color(0, 0, 255));
        cardapio.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        cardapio.setForeground(new java.awt.Color(255, 255, 255));
        cardapio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardapio.setText("Cardápio");
        jPanel1.add(cardapio);
        cardapio.setBounds(340, 60, 170, 40);

        btnPPrincipais.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnPPrincipais.setText("Pratos Principais");
        btnPPrincipais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPrincipaisActionPerformed(evt);
            }
        });
        jPanel1.add(btnPPrincipais);
        btnPPrincipais.setBounds(70, 150, 170, 29);

        btnPizzas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnPizzas.setText("Pizzas");
        btnPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPizzas);
        btnPizzas.setBounds(70, 190, 170, 29);

        btnBebidas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBebidas.setText("Bebidas");
        btnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasActionPerformed(evt);
            }
        });
        jPanel1.add(btnBebidas);
        btnBebidas.setBounds(70, 230, 170, 30);

        btnSobremesas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSobremesas.setText("Sobremesas");
        btnSobremesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobremesasActionPerformed(evt);
            }
        });
        jPanel1.add(btnSobremesas);
        btnSobremesas.setBounds(70, 270, 170, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurante Caprichos da Cozinha");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 20, 310, 30);

        btnAulas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAulas.setText("Aulas");
        btnAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAulasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAulas);
        btnAulas.setBounds(750, 80, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("Teste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 140, 110, 30);

        voltarTelaPrincipal.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        voltarTelaPrincipal.setText("VOLTAR");
        voltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTelaPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(voltarTelaPrincipal);
        voltarTelaPrincipal.setBounds(580, 300, 100, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 360);

        setSize(new java.awt.Dimension(881, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPPrincipaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPrincipaisActionPerformed
        // TODO add your handling code here:
        num=1;
        new TelaCarregamento_GUI().setVisible(true);
          
    }//GEN-LAST:event_btnPPrincipaisActionPerformed

    private void btnPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzasActionPerformed
        // TODO add your handling code here:
        num=2;
       new TelaCarregamento_GUI().setVisible(true);        
    }//GEN-LAST:event_btnPizzasActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        // TODO add your handling code here:
        num=3;
        new TelaCarregamento_GUI().setVisible(true);
    }//GEN-LAST:event_btnBebidasActionPerformed

    private void btnSobremesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobremesasActionPerformed
        // TODO add your handling code here:
        num=4;
        new TelaCarregamento_GUI().setVisible(true);
    }//GEN-LAST:event_btnSobremesasActionPerformed

    private void btnAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAulasActionPerformed
        // TODO add your handling code here:
        new Aulas_GUI().setVisible(true);
    }//GEN-LAST:event_btnAulasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Screen_GUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void voltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTelaPrincipalActionPerformed
        // TODO add your handling code here:
        dispose();
        new CadastroRestaurante_GUI().setVisible(true);
    }//GEN-LAST:event_voltarTelaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAulas;
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnPPrincipais;
    private javax.swing.JButton btnPizzas;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSobremesas;
    private javax.swing.JLabel cardapio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton voltarTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
